// Shared by the standalone game and the static Arabic-route generator.
export const AKSHIFHA_UI = {
  en: {
    metaTitle: 'Akshifha: Connect the Clues | Riddle Arabia',
    metaDescription: 'Connect two clues and uncover the contradiction. Five free original deduction cases in Arabic and English. No account or timer.',
    akSkip: 'Skip to the case', akHome: 'Riddle Arabia home', akNavigation: 'Game navigation',
    akGames: 'Games', akLanguage: 'Language', akEyebrow: 'A little evidence. A real aha moment.',
    akTitle: 'Akshifha', akSubtitle: 'Two clues. One contradiction. Can you connect them?',
    akPilot: 'Five-case pilot · Free · No account or timer',
    akDaily: 'Daily pick', akPractice: 'All five cases', akChallenge: 'Friend challenge',
    akRotation: 'The daily pick rotates through these five cases at midnight UTC. Cases repeat while we test the pilot.',
    akLoading: 'Opening the evidence…', akLoadHelp: 'If the case does not open, reload this page. No account is needed.',
    akNoScript: 'Akshifha needs JavaScript to check your clues. You can still browse our riddle collections.',
    akCollections: 'Browse riddles', akHow: 'How to play',
    akStepOne: 'Read the case and its rules.', akStepTwo: 'Select the two clues that work together.',
    akStepThree: 'Choose what they prove, then check your reasoning.',
    akRules: 'What you can rely on', akEvidence: '1. Connect two clues',
    akEvidenceHelp: 'Select exactly two. Unselect a clue to swap it. Everything you need is on this page.',
    akConclusion: '2. What do they prove?', akCheck: 'Check my reasoning',
    akHint: 'Give me a hint', akReveal: 'Show the explanation',
    akRevealQuestion: 'Reveal the answer and finish this case? It will be marked as revealed, not solved.',
    akRevealConfirm: 'Yes, reveal it', akRevealCancel: 'Keep thinking',
    akHints: 'Your hints', akResultLabel: 'Case debrief', akProof: 'The two connecting clues',
    akShare: 'Challenge a friend', akNext: 'Try another case', akReplay: 'Replay this case',
    akShareManual: 'Copy this spoiler-free challenge:', akCopied: 'Challenge copied. Your friend will get the same case.',
    akShared: 'Challenge shared.', akShareCancelled: 'Sharing cancelled. Your result is still here.',
    akShareUnavailable: 'Select and copy the challenge below.',
    akPersonal: 'Progress stays on this device. Results are personal practice, not verified leaderboard scores.',
    akProgress: 'Your casebook', akReset: 'Clear my progress',
    akResetQuestion: 'Clear only your Akshifha casebook on this device?', akResetConfirm: 'Clear casebook',
    akResetCancel: 'Keep it', akResetDone: 'Your local casebook has been cleared.',
    akStorageUnavailable: 'This browser cannot save progress. You can still play and share.',
    akInvalidLink: 'Part of that challenge link was not valid. We kept the case when possible and reset any invalid details.',
    akReady: 'Pick two clues and a conclusion to check your reasoning.',
    akSelection: '{count} of 2 clues selected.', akWrong: 'That combination does not prove this conclusion. Re-read the case rules, swap a clue, or use a hint.',
    akSolved: 'You connected it.', akAssisted: 'Case solved, with a little help.', akRevealed: 'The case, explained.',
    akStats: '{attempts} checks · {hints} hints', akKeyClue: 'Key evidence',
    akUnplayed: 'Not played', akStatusSolved: 'Solved', akStatusAssisted: 'Solved with hints', akStatusRevealed: 'Explanation viewed',
    akCompleted: '{count} of 5 cases explored', akCaseNumber: 'Case {number}', akDailyDate: 'Daily pick · {day} UTC',
    akPracticeMode: 'Practice case', akChallengeMode: 'You and your friend get the same evidence.',
    akPrivacy: 'Privacy', akFooter: 'Written for reasoning, not speed. Play in Arabic or English.',
    akFeedback: 'Found an unclear clue?', akFeedbackNote: 'Tell us the case number and what felt ambiguous.',
  },
  ar: {
    metaTitle: 'اكشفها: اربط الأدلة واكتشف التناقض | Riddle Arabia',
    metaDescription: 'اربط بين دليلين واكتشف التناقض. خمس قضايا منطقية أصلية ومجانية بالعربية والإنجليزية، بلا حساب أو مؤقّت.',
    akSkip: 'انتقل إلى القضية', akHome: 'الصفحة الرئيسية لرِدل أرابيا', akNavigation: 'التنقل بين الألعاب',
    akGames: 'الألعاب', akLanguage: 'اللغة', akEyebrow: 'دليل صغير. لحظة اكتشاف كبيرة.',
    akTitle: 'اكشفها', akSubtitle: 'دليلان وتناقض واحد. هل تربط بينهما؟',
    akPilot: 'نسخة تجريبية من خمس قضايا · مجانية · بلا حساب أو مؤقّت',
    akDaily: 'اختيار اليوم', akPractice: 'القضايا الخمس', akChallenge: 'تحدّي صديق',
    akRotation: 'يتغيّر اختيار اليوم عند منتصف الليل بتوقيت UTC، ويتناوب بين القضايا الخمس. تتكرّر القضايا خلال هذه النسخة التجريبية.',
    akLoading: 'نفتح ملف الأدلة…', akLoadHelp: 'إذا لم تظهر القضية، أعد تحميل الصفحة. لا تحتاج إلى حساب.',
    akNoScript: 'تحتاج «اكشفها» إلى JavaScript للتحقّق من الأدلة. يمكنك تصفّح مجموعات الألغاز أيضًا.',
    akCollections: 'تصفّح الألغاز', akHow: 'كيف تلعب؟',
    akStepOne: 'اقرأ القضية والقواعد التي تحكمها.', akStepTwo: 'اختر الدليلين اللذين يتكاملان.',
    akStepThree: 'حدّد ما يثبتانه، ثم تحقّق من استنتاجك.',
    akRules: 'ما يمكنك الاعتماد عليه', akEvidence: '١. اربط بين دليلين',
    akEvidenceHelp: 'اختر دليلين فقط. ألغِ اختيار أحدهما لتبديله. كل ما تحتاجه موجود في هذه الصفحة.',
    akConclusion: '٢. ماذا يثبتان؟', akCheck: 'تحقّق من استنتاجي',
    akHint: 'أعطني تلميحًا', akReveal: 'اعرض التفسير',
    akRevealQuestion: 'هل تريد كشف الحل وإنهاء القضية؟ ستُسجّل على أنك شاهدت التفسير، لا أنك حللتها.',
    akRevealConfirm: 'نعم، اكشف الحل', akRevealCancel: 'سأواصل التفكير',
    akHints: 'تلميحاتك', akResultLabel: 'خلاصة القضية', akProof: 'الدليلان المترابطان',
    akShare: 'تحدَّ صديقًا', akNext: 'جرّب قضية أخرى', akReplay: 'أعد لعب القضية',
    akShareManual: 'انسخ هذا التحدّي من دون كشف الحل:', akCopied: 'نُسخ التحدّي. سيحصل صديقك على القضية نفسها.',
    akShared: 'تمّت مشاركة التحدّي.', akShareCancelled: 'أُلغيت المشاركة. نتيجتك ما زالت هنا.',
    akShareUnavailable: 'حدّد التحدّي أدناه وانسخه.',
    akPersonal: 'يبقى تقدّمك على هذا الجهاز. النتائج للتدريب الشخصي وليست درجات موثّقة في لوحة منافسة.',
    akProgress: 'دفتر قضاياك', akReset: 'امسح تقدّمي',
    akResetQuestion: 'هل تريد مسح دفتر «اكشفها» من هذا الجهاز فقط؟', akResetConfirm: 'امسح الدفتر',
    akResetCancel: 'احتفظ به', akResetDone: 'مُسح دفتر قضاياك المحفوظ على هذا الجهاز.',
    akStorageUnavailable: 'لا يستطيع هذا المتصفّح حفظ التقدّم. يمكنك اللعب والمشاركة كالمعتاد.',
    akInvalidLink: 'جزء من رابط التحدّي غير صالح. أبقينا القضية إن أمكن، وأعدنا ضبط التفاصيل غير الصالحة.',
    akReady: 'اختر دليلين واستنتاجًا لتتحقّق من الحل.',
    akSelection: 'اخترت {count} من دليلين.', akWrong: 'هذا الجمع بين الأدلة لا يثبت الاستنتاج. راجع قواعد القضية، أو بدّل دليلًا، أو اطلب تلميحًا.',
    akSolved: 'ربطت الأدلة وكشفتها.', akAssisted: 'حللت القضية مع قليل من المساعدة.', akRevealed: 'إليك تفسير القضية.',
    akStats: '{attempts} محاولات تحقّق · {hints} تلميحات', akKeyClue: 'دليل حاسم',
    akUnplayed: 'لم تلعبها بعد', akStatusSolved: 'محلولة', akStatusAssisted: 'محلولة بتلميحات', akStatusRevealed: 'شاهدت التفسير',
    akCompleted: 'استكشفت {count} من خمس قضايا', akCaseNumber: 'القضية {number}', akDailyDate: 'اختيار اليوم · {day} UTC',
    akPracticeMode: 'قضية للتدريب', akChallengeMode: 'أنت وصديقك أمام الأدلة نفسها.',
    akPrivacy: 'الخصوصية', akFooter: 'للتفكير، لا للسباق. العب بالعربية أو الإنجليزية.',
    akFeedback: 'هل وجدت دليلًا غير واضح؟', akFeedbackNote: 'اذكر رقم القضية وما بدا لك غامضًا.',
  },
};
