#!/usr/bin/env python3
import json

# Format: (subcategory_en, subcategory_ar, difficulty, q_en, q_ar, a_en, a_ar)

QUESTIONS = [
# ── Part 1: Group Dynamic (Mode A) ───────────────────────────────
('Group Dynamic','ديناميكية المجموعة','medium',
 'If this person started a cult tomorrow, what would be the "core value" they\'d convince everyone to follow?',
 'لو أسّس هذا الشخص طائفة غداً، ما هي "القيمة الأساسية" التي سيُقنع الجميع باتباعها؟',
 'Discuss as a group — there is no single right answer.',
 'ناقشوا كمجموعة — لا توجد إجابة صحيحة واحدة.'),

('Group Dynamic','ديناميكية المجموعة','medium',
 'If this person had to lie to a CEO to save the group, would they be a convincing liar or crack immediately?',
 'لو اضطر هذا الشخص للكذب على رئيس شركة لإنقاذ المجموعة، هل سيكون كاذباً مقنعاً أم سينهار فوراً؟',
 'Discuss as a group — there is no single right answer.',
 'ناقشوا كمجموعة — لا توجد إجابة صحيحة واحدة.'),

('Group Dynamic','ديناميكية المجموعة','medium',
 'Which friend is most likely to have a "secret project" or side hustle they haven\'t told anyone about yet?',
 'أي صديق من المرجح أن يكون لديه "مشروع سري" أو عمل جانبي لم يُخبر أحداً عنه بعد؟',
 'Discuss as a group — there is no single right answer.',
 'ناقشوا كمجموعة — لا توجد إجابة صحيحة واحدة.'),

('Group Dynamic','ديناميكية المجموعة','medium',
 'If the group were trapped in a movie, who would be the first to sacrifice themselves for the team?',
 'لو كانت المجموعة محاصرة في فيلم، من سيكون أول من يضحي بنفسه من أجل الفريق؟',
 'Discuss as a group — there is no single right answer.',
 'ناقشوا كمجموعة — لا توجد إجابة صحيحة واحدة.'),

('Group Dynamic','ديناميكية المجموعة','easy',
 'Who in the group has the most "expensive" taste but the "cheapest" daily habits?',
 'من في المجموعة لديه أكثر الأذواق "باهظة" لكن أرخص العادات اليومية؟',
 'Discuss as a group — there is no single right answer.',
 'ناقشوا كمجموعة — لا توجد إجابة صحيحة واحدة.'),

('Group Dynamic','ديناميكية المجموعة','medium',
 'If this person won 10 million dollars, who is the last person in this room they would tell?',
 'لو ربح هذا الشخص 10 ملايين دولار، من سيكون آخر شخص في هذه الغرفة يُخبره؟',
 'Discuss as a group — there is no single right answer.',
 'ناقشوا كمجموعة — لا توجد إجابة صحيحة واحدة.'),

('Group Dynamic','ديناميكية المجموعة','hard',
 'Who is the "silent architect"—the one who makes the plans happen without taking any credit?',
 'من هو "المهندس الصامت" — الشخص الذي يُنفّذ الخطط دون أن يأخذ أي فضل؟',
 'Discuss as a group — there is no single right answer.',
 'ناقشوا كمجموعة — لا توجد إجابة صحيحة واحدة.'),

('Group Dynamic','ديناميكية المجموعة','hard',
 'If this person\'s browser history from 3:00 AM was made public, what would be the most confusing thing on it?',
 'لو أُعلن عن سجل تصفح هذا الشخص في الساعة 3 صباحاً، ما أكثر شيء محيّر فيه؟',
 'Discuss as a group — there is no single right answer.',
 'ناقشوا كمجموعة — لا توجد إجابة صحيحة واحدة.'),

('Group Dynamic','ديناميكية المجموعة','medium',
 'Who is most likely to accidentally become a millionaire through a weird tech glitch or lucky mistake?',
 'من الأكثر احتمالاً أن يصبح مليونيراً بالصدفة بسبب خطأ تقني غريب أو حظ عجيب؟',
 'Discuss as a group — there is no single right answer.',
 'ناقشوا كمجموعة — لا توجد إجابة صحيحة واحدة.'),

('Group Dynamic','ديناميكية المجموعة','medium',
 'If we were all on a reality TV show, who would be the "villain" that the audience secretly loves?',
 'لو كنّا جميعاً في برنامج تلفزيوني للواقع، من سيكون "الشرير" الذي يُحبه الجمهور سراً؟',
 'Discuss as a group — there is no single right answer.',
 'ناقشوا كمجموعة — لا توجد إجابة صحيحة واحدة.'),

('Group Dynamic','ديناميكية المجموعة','medium',
 'What is this person\'s "social battery" tell? How do you know exactly when they are done with the party?',
 'ما هي علامة نفاد "طاقة التواصل الاجتماعي" لهذا الشخص؟ كيف تعرف متى انتهى توده للحفلة؟',
 'Discuss as a group — there is no single right answer.',
 'ناقشوا كمجموعة — لا توجد إجابة صحيحة واحدة.'),

('Group Dynamic','ديناميكية المجموعة','hard',
 'If this person is unusually quiet, are they angry, tired, or just over-thinking a text they sent?',
 'لو كان هذا الشخص صامتاً بشكل غير معتاد، هل هو غاضب أم متعب أم يُفكر زيادة في رسالة أرسلها؟',
 'Discuss as a group — there is no single right answer.',
 'ناقشوا كمجموعة — لا توجد إجابة صحيحة واحدة.'),

('Group Dynamic','ديناميكية المجموعة','medium',
 'Which friend would you trust to hide a secret, and which one would you trust to defend you in court?',
 'أي صديق ستثق به لإخفاء سر، وأيهم لك الدفاع عنك أمام القضاء؟',
 'Discuss as a group — there is no single right answer.',
 'ناقشوا كمجموعة — لا توجد إجابة صحيحة واحدة.'),

('Group Dynamic','ديناميكية المجموعة','easy',
 'What is the one topic you know never to bring up with this person to avoid a 2-hour argument?',
 'ما الموضوع الذي تعرف أنك لا تُثيره أبداً مع هذا الشخص لتتجنب جدالاً لساعتين؟',
 'Discuss as a group — there is no single right answer.',
 'ناقشوا كمجموعة — لا توجد إجابة صحيحة واحدة.'),

('Group Dynamic','ديناميكية المجموعة','medium',
 'If this person were a ghost, who is the first person they would choose to haunt just for fun?',
 'لو كان هذا الشخص شبحاً، من هو أول شخص سيختار إزعاجه للمتعة فقط؟',
 'Discuss as a group — there is no single right answer.',
 'ناقشوا كمجموعة — لا توجد إجابة صحيحة واحدة.'),

('Group Dynamic','ديناميكية المجموعة','hard',
 'Who in the group is most likely to be a secret agent in real life?',
 'من في المجموعة الأكثر احتمالاً أن يكون عميلاً سرياً في الحياة الحقيقية؟',
 'Discuss as a group — there is no single right answer.',
 'ناقشوا كمجموعة — لا توجد إجابة صحيحة واحدة.'),

('Group Dynamic','ديناميكية المجموعة','medium',
 'What is the "unspoken rule" this person has for their personal space that everyone just knows?',
 'ما هي "القاعدة غير المُعلنة" لهذا الشخص بشأن مساحته الشخصية التي يعرفها الجميع؟',
 'Discuss as a group — there is no single right answer.',
 'ناقشوا كمجموعة — لا توجد إجابة صحيحة واحدة.'),

('Group Dynamic','ديناميكية المجموعة','medium',
 'If this person had a "warning label" attached to them, what would it say in tiny print?',
 'لو كان لهذا الشخص "ملصق تحذير"، ماذا سيكتب فيه بخط صغير؟',
 'Discuss as a group — there is no single right answer.',
 'ناقشوا كمجموعة — لا توجد إجابة صحيحة واحدة.'),

('Group Dynamic','ديناميكية المجموعة','medium',
 'Who is most likely to ghost the entire group for a month and then reappear like nothing happened?',
 'من الأرجح أن يختفي عن المجموعة لشهر كامل ثم يعود كأن شيئاً لم يكن؟',
 'Discuss as a group — there is no single right answer.',
 'ناقشوا كمجموعة — لا توجد إجابة صحيحة واحدة.'),

('Group Dynamic','ديناميكية المجموعة','hard',
 'What is the one thing this person is most insecure about, even though the group thinks it\'s a strength?',
 'ما الشيء الذي يشعر هذا الشخص بعدم الأمان حوله أكثر، رغم أن المجموعة تعتبره نقطة قوة؟',
 'Discuss as a group — there is no single right answer.',
 'ناقشوا كمجموعة — لا توجد إجابة صحيحة واحدة.'),

('Group Dynamic','ديناميكية المجموعة','easy',
 'If this person\'s phone was at 1%, what is the last app they would check before it died?',
 'لو كانت بطارية هاتف هذا الشخص عند 1%، ما آخر تطبيق سيتحقق منه قبل انطفائه؟',
 'Discuss as a group — there is no single right answer.',
 'ناقشوا كمجموعة — لا توجد إجابة صحيحة واحدة.'),

('Group Dynamic','ديناميكية المجموعة','medium',
 'Who is most likely to buy a high-end luxury item they can\'t afford because of an AI-generated ad?',
 'من الأرجح أن يشتري منتجاً فاخراً لا يستطيع تحمّل تكلفته بسبب إعلان مُنشأ بالذكاء الاصطناعي؟',
 'Discuss as a group — there is no single right answer.',
 'ناقشوا كمجموعة — لا توجد إجابة صحيحة واحدة.'),

('Group Dynamic','ديناميكية المجموعة','medium',
 'If the internet disappeared tomorrow, which friend would thrive and who would lose their mind?',
 'لو اختفى الإنترنت غداً، أي صديق سيزدهر وأيهم سيُجنّ؟',
 'Discuss as a group — there is no single right answer.',
 'ناقشوا كمجموعة — لا توجد إجابة صحيحة واحدة.'),

('Group Dynamic','ديناميكية المجموعة','medium',
 'Who has the most "organized" digital life but the most chaotic physical room or desk?',
 'من لديه أكثر حياة رقمية "منظمة" لكن أكثر غرفة أو مكتب فوضى؟',
 'Discuss as a group — there is no single right answer.',
 'ناقشوا كمجموعة — لا توجد إجابة صحيحة واحدة.'),

('Group Dynamic','ديناميكية المجموعة','hard',
 'If this person were a piece of tech, would they be a high-end watch or a glitchy smart-bulb?',
 'لو كان هذا الشخص قطعة تقنية، هل سيكون ساعة فاخرة أم مصباحاً ذكياً معيباً؟',
 'Discuss as a group — there is no single right answer.',
 'ناقشوا كمجموعة — لا توجد إجابة صحيحة واحدة.'),

('Group Dynamic','ديناميكية المجموعة','easy',
 'Who is the "gadget whisperer" you call when the Wi-Fi dies or the TV won\'t connect?',
 'من هو "مُروّض الأجهزة" الذي تتصل به عند انقطاع الواي فاي أو عطل التلفاز؟',
 'Discuss as a group — there is no single right answer.',
 'ناقشوا كمجموعة — لا توجد إجابة صحيحة واحدة.'),

('Group Dynamic','ديناميكية المجموعة','medium',
 'Which friend is most likely to fall for a deep-fake scam or a "get rich quick" bot?',
 'أي صديق الأكثر عرضة للوقوع ضحية احتيال بالذكاء الاصطناعي أو روبوت "الثراء السريع"؟',
 'Discuss as a group — there is no single right answer.',
 'ناقشوا كمجموعة — لا توجد إجابة صحيحة واحدة.'),

('Group Dynamic','ديناميكية المجموعة','hard',
 'If we were all AI robots, what would be this person\'s recurring "system error"?',
 'لو كنّا جميعاً روبوتات ذكاء اصطناعي، ما هو "خطأ النظام" المتكرر لهذا الشخص؟',
 'Discuss as a group — there is no single right answer.',
 'ناقشوا كمجموعة — لا توجد إجابة صحيحة واحدة.'),

('Group Dynamic','ديناميكية المجموعة','medium',
 'Who is most likely to be "famous" in 5 years for something completely random?',
 'من الأرجح أن يصبح "مشهوراً" خلال 5 سنوات بسبب شيء عشوائي تماماً؟',
 'Discuss as a group — there is no single right answer.',
 'ناقشوا كمجموعة — لا توجد إجابة صحيحة واحدة.'),

('Group Dynamic','ديناميكية المجموعة','easy',
 'What is the one fashion trend this person hates but secretly looks great in?',
 'ما هو اتجاه الموضة الذي يكرهه هذا الشخص لكنه يبدو رائعاً فيه سراً؟',
 'Discuss as a group — there is no single right answer.',
 'ناقشوا كمجموعة — لا توجد إجابة صحيحة واحدة.'),

('Group Dynamic','ديناميكية المجموعة','hard',
 'If you were in a crisis at 4:00 AM, would this person answer or is "Do Not Disturb" always on?',
 'لو كنتَ في أزمة الساعة 4 صباحاً، هل سيردّ هذا الشخص أم أن وضع "عدم الإزعاج" دائماً مفعّل لديه؟',
 'Discuss as a group — there is no single right answer.',
 'ناقشوا كمجموعة — لا توجد إجابة صحيحة واحدة.'),

('Group Dynamic','ديناميكية المجموعة','medium',
 'What is the one "bad habit" this person has that the group has collectively agreed to ignore?',
 'ما هي "العادة السيئة" الواحدة لهذا الشخص التي اتفقت المجموعة ضمنياً على تجاهلها؟',
 'Discuss as a group — there is no single right answer.',
 'ناقشوا كمجموعة — لا توجد إجابة صحيحة واحدة.'),

('Group Dynamic','ديناميكية المجموعة','medium',
 'If this person had to pick one friend to go on a 10-year space mission with, who would it be?',
 'لو اضطر هذا الشخص لاختيار صديق واحد لمهمة فضائية مدتها 10 سنوات، من سيختار؟',
 'Discuss as a group — there is no single right answer.',
 'ناقشوا كمجموعة — لا توجد إجابة صحيحة واحدة.'),

('Group Dynamic','ديناميكية المجموعة','hard',
 'Who is the person that "holds the keys" to the group\'s deepest secrets?',
 'من هو الشخص الذي يحمل "مفاتيح" أعمق أسرار المجموعة؟',
 'Discuss as a group — there is no single right answer.',
 'ناقشوا كمجموعة — لا توجد إجابة صحيحة واحدة.'),

('Group Dynamic','ديناميكية المجموعة','medium',
 'If the group got into a fight, who is the "peacekeeper" and who "adds fuel to the fire"?',
 'لو وقع خلاف في المجموعة، من هو "صانع السلام" ومن هو "الذي يُذكي النار"؟',
 'Discuss as a group — there is no single right answer.',
 'ناقشوا كمجموعة — لا توجد إجابة صحيحة واحدة.'),

('Group Dynamic','ديناميكية المجموعة','hard',
 'What is the most "heroic" thing this person has ever done that they never talk about?',
 'ما أكثر شيء "بطولي" فعله هذا الشخص ولا يتحدث عنه أبداً؟',
 'Discuss as a group — there is no single right answer.',
 'ناقشوا كمجموعة — لا توجد إجابة صحيحة واحدة.'),

('Group Dynamic','ديناميكية المجموعة','medium',
 'Who is the most likely to remember a small detail you mentioned six months ago?',
 'من الأرجح أن يتذكر تفصيلة صغيرة ذكرتها قبل ستة أشهر؟',
 'Discuss as a group — there is no single right answer.',
 'ناقشوا كمجموعة — لا توجد إجابة صحيحة واحدة.'),

('Group Dynamic','ديناميكية المجموعة','medium',
 'If the group split up, who would be the "glue" that keeps everyone in touch?',
 'لو تفرّقت المجموعة، من سيكون "الغراء" الذي يبقي الجميع على تواصل؟',
 'Discuss as a group — there is no single right answer.',
 'ناقشوا كمجموعة — لا توجد إجابة صحيحة واحدة.'),

('Group Dynamic','ديناميكية المجموعة','medium',
 'What is this person\'s "love language" in friendship—acts of service or just showing up?',
 'ما هي "لغة الحب" الصداقية لهذا الشخص — أفعال الخدمة أم مجرد الحضور؟',
 'Discuss as a group — there is no single right answer.',
 'ناقشوا كمجموعة — لا توجد إجابة صحيحة واحدة.'),

('Group Dynamic','ديناميكية المجموعة','easy',
 'If you had to describe this person\'s "vibe" in exactly three words, what would they be?',
 'لو وصفتَ "طاقة" هذا الشخص بثلاث كلمات بالضبط، ما هي؟',
 'Discuss as a group — there is no single right answer.',
 'ناقشوا كمجموعة — لا توجد إجابة صحيحة واحدة.'),

('Group Dynamic','ديناميكية المجموعة','hard',
 'If this person could trade lives with anyone in this room for a week, who would they choose?',
 'لو استطاع هذا الشخص تبادل الحياة مع أي شخص في هذه الغرفة لأسبوع، من سيختار؟',
 'Discuss as a group — there is no single right answer.',
 'ناقشوا كمجموعة — لا توجد إجابة صحيحة واحدة.'),

('Group Dynamic','ديناميكية المجموعة','hard',
 'What is the one thing this person thinks they are great at, but the group knows they are terrible at?',
 'ما الشيء الواحد الذي يعتقد هذا الشخص أنه بارع فيه، لكن المجموعة تعرف أنه سيء فيه؟',
 'Discuss as a group — there is no single right answer.',
 'ناقشوا كمجموعة — لا توجد إجابة صحيحة واحدة.'),

('Group Dynamic','ديناميكية المجموعة','easy',
 'Who is most likely to "accidentally" forget to pay their share of the bill?',
 'من الأرجح أن "ينسى عن طريق الخطأ" دفع حصته من الفاتورة؟',
 'Discuss as a group — there is no single right answer.',
 'ناقشوا كمجموعة — لا توجد إجابة صحيحة واحدة.'),

('Group Dynamic','ديناميكية المجموعة','hard',
 'If this person moved to a different country, would they stay in touch or start a brand-new life?',
 'لو انتقل هذا الشخص لبلد مختلف، هل سيبقى على تواصل أم سيبدأ حياة جديدة كلياً؟',
 'Discuss as a group — there is no single right answer.',
 'ناقشوا كمجموعة — لا توجد إجابة صحيحة واحدة.'),

('Group Dynamic','ديناميكية المجموعة','medium',
 'Who is the most likely to have a secret social media account that no one knows about?',
 'من الأرجح أن يمتلك حساباً سرياً على وسائل التواصل الاجتماعي لا يعرفه أحد؟',
 'Discuss as a group — there is no single right answer.',
 'ناقشوا كمجموعة — لا توجد إجابة صحيحة واحدة.'),

('Group Dynamic','ديناميكية المجموعة','very-advanced',
 'What is the "peak" memory of this person that the group will still be talking about in 20 years?',
 'ما الذكرى "الذروة" لهذا الشخص التي ستظل المجموعة تتحدث عنها بعد 20 عاماً؟',
 'Discuss as a group — there is no single right answer.',
 'ناقشوا كمجموعة — لا توجد إجابة صحيحة واحدة.'),

('Group Dynamic','ديناميكية المجموعة','easy',
 'If this person were a flavor of ice cream, would they be classic vanilla or an experimental flavor?',
 'لو كان هذا الشخص نكهة آيس كريم، هل سيكون الفانيليا الكلاسيكية أم نكهة تجريبية؟',
 'Discuss as a group — there is no single right answer.',
 'ناقشوا كمجموعة — لا توجد إجابة صحيحة واحدة.'),

('Group Dynamic','ديناميكية المجموعة','medium',
 'Who is most likely to survive a zombie apocalypse based purely on their stubbornness?',
 'من الأرجح أن ينجو من غزو الزومبي بناءً على عناده البحت؟',
 'Discuss as a group — there is no single right answer.',
 'ناقشوا كمجموعة — لا توجد إجابة صحيحة واحدة.'),

('Group Dynamic','ديناميكية المجموعة','hard',
 'What is the one thing this person would change about the group if they had a magic wand?',
 'ما الشيء الواحد الذي سيُغيّره هذا الشخص في المجموعة لو امتلك عصا سحرية؟',
 'Discuss as a group — there is no single right answer.',
 'ناقشوا كمجموعة — لا توجد إجابة صحيحة واحدة.'),

('Group Dynamic','ديناميكية المجموعة','hard',
 'If the group had to choose a "leader" for an emergency, would it be this person?',
 'لو اضطرت المجموعة لاختيار "قائد" في حالة طوارئ، هل سيكون هذا الشخص؟',
 'Discuss as a group — there is no single right answer.',
 'ناقشوا كمجموعة — لا توجد إجابة صحيحة واحدة.'),

# ── Part 2: Soul Link (Mode B) ────────────────────────────────────
('Soul Link','رابط الروح','medium',
 'When I\'m on my phone in a social setting, am I reading or using it as a "social shield"?',
 'حين أكون على هاتفي في تجمع اجتماعي، هل أقرأ فعلاً أم أستخدمه "درعاً اجتماعياً"؟',
 'Only the player can confirm the right answer.',
 'فقط اللاعب يستطيع تأكيد الإجابة الصحيحة.'),

('Soul Link','رابط الروح','medium',
 'What is the one specific noise or sound that makes me instantly irritated?',
 'ما الضوضاء أو الصوت المحدد الذي يُثير انزعاجي فوراً؟',
 'Only the player can confirm the right answer.',
 'فقط اللاعب يستطيع تأكيد الإجابة الصحيحة.'),

('Soul Link','رابط الروح','easy',
 'If I\'m looking at a menu for 5 minutes, am I struggling to choose or just reading the ingredients?',
 'لو كنت أتصفح القائمة لـ5 دقائق، هل أجد صعوبة في الاختيار أم أقرأ المكونات فقط؟',
 'Only the player can confirm the right answer.',
 'فقط اللاعب يستطيع تأكيد الإجابة الصحيحة.'),

('Soul Link','رابط الروح','hard',
 'What is the "tell" that shows I\'m bored of a conversation without me saying a word?',
 'ما هي "العلامة" التي تدل على مللي من محادثة ما دون أن أقول كلمة؟',
 'Only the player can confirm the right answer.',
 'فقط اللاعب يستطيع تأكيد الإجابة الصحيحة.'),

('Soul Link','رابط الروح','medium',
 'How do I react when someone gives me a compliment that I don\'t think I deserve?',
 'كيف أتصرف حين يُثني عليّ شخص بثناء لا أرى نفسي أستحقه؟',
 'Only the player can confirm the right answer.',
 'فقط اللاعب يستطيع تأكيد الإجابة الصحيحة.'),

('Soul Link','رابط الروح','medium',
 'Am I more likely to over-prepare for a small task or under-prepare for a big one?',
 'هل أُفرط في التحضير لمهمة صغيرة أم أُقصّر في التحضير لمهمة كبيرة؟',
 'Only the player can confirm the right answer.',
 'فقط اللاعب يستطيع تأكيد الإجابة الصحيحة.'),

('Soul Link','رابط الروح','easy',
 'What is my "guilty pleasure" purchase that I know is a waste of money?',
 'ما هو مشتراي "اللذة المحرّمة" الذي أعرف أنه إهدار للمال؟',
 'Only the player can confirm the right answer.',
 'فقط اللاعب يستطيع تأكيد الإجابة الصحيحة.'),

('Soul Link','رابط الروح','medium',
 'If I have a free hour with no responsibilities, what is the first thing I instinctively do?',
 'لو أُتيح لي ساعة حرة بلا مسؤوليات، ما أول شيء أفعله بشكل غريزي؟',
 'Only the player can confirm the right answer.',
 'فقط اللاعب يستطيع تأكيد الإجابة الصحيحة.'),

('Soul Link','رابط الروح','easy',
 'When I\'m driving or walking alone, do I listen to music, a podcast, or nothing at all?',
 'حين أقود أو أمشي وحدي، هل أستمع إلى موسيقى أم بودكاست أم لا شيء على الإطلاق؟',
 'Only the player can confirm the right answer.',
 'فقط اللاعب يستطيع تأكيد الإجابة الصحيحة.'),

('Soul Link','رابط الروح','hard',
 'What is the one thing in my house that I am weirdly protective or territorial about?',
 'ما الشيء الوحيد في منزلي الذي أكون بشأنه حذراً وإقليمياً بشكل غريب؟',
 'Only the player can confirm the right answer.',
 'فقط اللاعب يستطيع تأكيد الإجابة الصحيحة.'),

('Soul Link','رابط الروح','medium',
 'What is the one "dream job" I had as a kid that I still secretly think I\'d be good at?',
 'ما "الوظيفة الحلم" التي تمنيتها طفلاً والتي لا أزال أعتقد سراً أنني سأجيد أداءها؟',
 'Only the player can confirm the right answer.',
 'فقط اللاعب يستطيع تأكيد الإجابة الصحيحة.'),

('Soul Link','رابط الروح','medium',
 'If I\'m frustrated with work, do I vent about it immediately or process it alone?',
 'حين أشعر بالإحباط من العمل، هل أتذمّر فوراً أم أعالج الأمر بمفردي؟',
 'Only the player can confirm the right answer.',
 'فقط اللاعب يستطيع تأكيد الإجابة الصحيحة.'),

('Soul Link','رابط الروح','hard',
 'What is my biggest "productivity hack" that actually doesn\'t work?',
 'ما هي أكبر "حيلة إنتاجية" لديّ التي لا تنجح في الواقع؟',
 'Only the player can confirm the right answer.',
 'فقط اللاعب يستطيع تأكيد الإجابة الصحيحة.'),

('Soul Link','رابط الروح','hard',
 'Which of my past failures do I actually consider my "best" lesson?',
 'أي إخفاقاتي الماضية أعدّه في الحقيقة "أفضل" درس تعلمته؟',
 'Only the player can confirm the right answer.',
 'فقط اللاعب يستطيع تأكيد الإجابة الصحيحة.'),

('Soul Link','رابط الروح','medium',
 'If I started a YouTube channel tomorrow, what would be the specific niche or topic?',
 'لو أسّستُ قناة يوتيوب غداً، ما سيكون موضوعها أو تخصصها المحدد؟',
 'Only the player can confirm the right answer.',
 'فقط اللاعب يستطيع تأكيد الإجابة الصحيحة.'),

('Soul Link','رابط الروح','hard',
 'What is the one professional "buzzword" that makes me lose respect for someone?',
 'ما هي "الكلمة الرنانة" المهنية الواحدة التي تجعلني أفقد احترامي لشخص ما؟',
 'Only the player can confirm the right answer.',
 'فقط اللاعب يستطيع تأكيد الإجابة الصحيحة.'),

('Soul Link','رابط الروح','medium',
 'Do I value "hard work" or "smart work" more?',
 'هل أُقدّر "العمل الجاد" أكثر أم "العمل الذكي"؟',
 'Only the player can confirm the right answer.',
 'فقط اللاعب يستطيع تأكيد الإجابة الصحيحة.'),

('Soul Link','رابط الروح','medium',
 'What is the one goal I\'ve talked about so much that you\'re tired of hearing it?',
 'ما الهدف الذي تحدثت عنه كثيراً لدرجة أنك سئمت من سماعه؟',
 'Only the player can confirm the right answer.',
 'فقط اللاعب يستطيع تأكيد الإجابة الصحيحة.'),

('Soul Link','رابط الروح','medium',
 'Would I rather be the "boss" of a small team or a "specialist" in a giant company?',
 'هل أفضّل أن أكون "رئيساً" لفريق صغير أم "متخصصاً" في شركة عملاقة؟',
 'Only the player can confirm the right answer.',
 'فقط اللاعب يستطيع تأكيد الإجابة الصحيحة.'),

('Soul Link','رابط الروح','hard',
 'What is the most "impulsive" career or business decision I\'ve ever made?',
 'ما أكثر قرار مهني أو تجاري "اندفاعي" اتخذته في حياتي؟',
 'Only the player can confirm the right answer.',
 'فقط اللاعب يستطيع تأكيد الإجابة الصحيحة.'),

('Soul Link','رابط الروح','hard',
 'What is the one thing a person can do to instantly lose my trust forever?',
 'ما الشيء الواحد الذي يستطيع شخص ما فعله ليفقد ثقتي به للأبد فوراً؟',
 'Only the player can confirm the right answer.',
 'فقط اللاعب يستطيع تأكيد الإجابة الصحيحة.'),

('Soul Link','رابط الروح','hard',
 'How do I act when I\'m genuinely proud of someone but don\'t want to be "mushy"?',
 'كيف أتصرف حين أفخر بشخص ما فعلاً لكنني لا أريد أن أكون "عاطفياً مفرطاً"؟',
 'Only the player can confirm the right answer.',
 'فقط اللاعب يستطيع تأكيد الإجابة الصحيحة.'),

('Soul Link','رابط الروح','medium',
 'If we had a huge argument, what is the "peace offering" that would break my ice?',
 'لو وقع بيننا خلاف كبير، ما هي "هدية السلام" التي ستكسر الجليد معي؟',
 'Only the player can confirm the right answer.',
 'فقط اللاعب يستطيع تأكيد الإجابة الصحيحة.'),

('Soul Link','رابط الروح','hard',
 'What is the one personality trait I look for in a friend that I feel I am lacking?',
 'ما هي السمة الشخصية الواحدة التي أبحث عنها في صديق وأشعر أنني أفتقر إليها؟',
 'Only the player can confirm the right answer.',
 'فقط اللاعب يستطيع تأكيد الإجابة الصحيحة.'),

('Soul Link','رابط الروح','medium',
 'Am I the type to hold a grudge for years or forget the fight after a week?',
 'هل أنا من النوع الذي يحمل ضغينة لسنوات أم ينسى الشجار بعد أسبوع؟',
 'Only the player can confirm the right answer.',
 'فقط اللاعب يستطيع تأكيد الإجابة الصحيحة.'),

('Soul Link','رابط الروح','medium',
 'What is the "sweetest" thing someone has ever done for me that I still talk about?',
 'ما أحلى شيء فعله أحدهم لي ولا أزال أتحدث عنه حتى اليوم؟',
 'Only the player can confirm the right answer.',
 'فقط اللاعب يستطيع تأكيد الإجابة الصحيحة.'),

('Soul Link','رابط الروح','medium',
 'When I\'m stressed, do I need "tough love" or "soft comfort"?',
 'حين أكون تحت ضغط، هل أحتاج إلى "حب صارم" أم "مواساة لطيفة"؟',
 'Only the player can confirm the right answer.',
 'فقط اللاعب يستطيع تأكيد الإجابة الصحيحة.'),

('Soul Link','رابط الروح','hard',
 'What is the one topic that can make me go from 0 to 100 in seconds?',
 'ما الموضوع الواحد الذي يمكنه جعلي أنتقل من 0 إلى 100 في ثوانٍ؟',
 'Only the player can confirm the right answer.',
 'فقط اللاعب يستطيع تأكيد الإجابة الصحيحة.'),

('Soul Link','رابط الروح','hard',
 'Who is the one person in my life (dead or alive) that I am still trying to make proud?',
 'من هو الشخص الواحد في حياتي (حياً أو ميتاً) الذي لا أزال أسعى لإرضائه؟',
 'Only the player can confirm the right answer.',
 'فقط اللاعب يستطيع تأكيد الإجابة الصحيحة.'),

('Soul Link','رابط الروح','hard',
 'If I were to go "off the grid" tomorrow, who is the only person I\'d actually tell?',
 'لو قررت الاختفاء عن العالم غداً، من هو الشخص الوحيد الذي سأُخبره فعلاً؟',
 'Only the player can confirm the right answer.',
 'فقط اللاعب يستطيع تأكيد الإجابة الصحيحة.'),

('Soul Link','رابط الروح','hard',
 'Do I believe people can truly change, or do I think everyone stays the same deep down?',
 'هل أؤمن أن الناس يمكنهم التغيّر فعلاً، أم أعتقد أن الجميع يبقى نفسه في أعماقه؟',
 'Only the player can confirm the right answer.',
 'فقط اللاعب يستطيع تأكيد الإجابة الصحيحة.'),

('Soul Link','رابط الروح','hard',
 'What is my "superstition" (even if I say I\'m not superstitious)?',
 'ما هي خرافتي الشخصية (حتى لو قلت أنني لست خرافياً)؟',
 'Only the player can confirm the right answer.',
 'فقط اللاعب يستطيع تأكيد الإجابة الصحيحة.'),

('Soul Link','رابط الروح','very-advanced',
 'If I could know the "absolute truth" to one mystery in the world, which one would I pick?',
 'لو أمكنني معرفة "الحقيقة المطلقة" لغموض واحد في العالم، أيها سأختار؟',
 'Only the player can confirm the right answer.',
 'فقط اللاعب يستطيع تأكيد الإجابة الصحيحة.'),

('Soul Link','رابط الروح','very-advanced',
 'What is the one thing I want to be remembered for after I\'m gone?',
 'ما الشيء الواحد الذي أريد أن يُتذكّر عني بعد رحيلي؟',
 'Only the player can confirm the right answer.',
 'فقط اللاعب يستطيع تأكيد الإجابة الصحيحة.'),

('Soul Link','رابط الروح','hard',
 'Do I make decisions based on "what could go right" or "what could go wrong"?',
 'هل أتخذ قراراتي بناءً على "ما يمكن أن يسير بشكل صحيح" أم "ما يمكن أن يسوء"؟',
 'Only the player can confirm the right answer.',
 'فقط اللاعب يستطيع تأكيد الإجابة الصحيحة.'),

('Soul Link','رابط الروح','very-advanced',
 'What is my personal definition of "success" in exactly one sentence?',
 'ما تعريفي الشخصي لـ"النجاح" في جملة واحدة بالضبط؟',
 'Only the player can confirm the right answer.',
 'فقط اللاعب يستطيع تأكيد الإجابة الصحيحة.'),

('Soul Link','رابط الروح','very-advanced',
 'If I could rewrite one day of my life, which one would it be?',
 'لو أمكنني إعادة كتابة يوم واحد من حياتي، أي يوم سيكون؟',
 'Only the player can confirm the right answer.',
 'فقط اللاعب يستطيع تأكيد الإجابة الصحيحة.'),

('Soul Link','رابط الروح','hard',
 'What is the most "unpopular opinion" I hold that I will defend to the death?',
 'ما هو أكثر "رأي غير شائع" أحمله وسأدافع عنه حتى الموت؟',
 'Only the player can confirm the right answer.',
 'فقط اللاعب يستطيع تأكيد الإجابة الصحيحة.'),

('Soul Link','رابط الروح','medium',
 'Do I think I am more like my mother or my father in terms of personality?',
 'هل أعتقد أنني أشبه أمي أم أبي من حيث الشخصية؟',
 'Only the player can confirm the right answer.',
 'فقط اللاعب يستطيع تأكيد الإجابة الصحيحة.'),

('Soul Link','رابط الروح','very-advanced',
 'What is the one thing about the world today that keeps me up at night?',
 'ما الشيء الواحد في عالم اليوم الذي يُبقيني مستيقظاً في الليل؟',
 'Only the player can confirm the right answer.',
 'فقط اللاعب يستطيع تأكيد الإجابة الصحيحة.'),

('Soul Link','رابط الروح','easy',
 'What is my "regular order" at a place we go to often?',
 'ما هو طلبي "المعتاد" في المكان الذي نذهب إليه كثيراً؟',
 'Only the player can confirm the right answer.',
 'فقط اللاعب يستطيع تأكيد الإجابة الصحيحة.'),

('Soul Link','رابط الروح','easy',
 'What is the one piece of clothing I own that you absolutely hate?',
 'ما هي القطعة الملبسية الواحدة التي أمتلكها والتي تكرهها تماماً؟',
 'Only the player can confirm the right answer.',
 'فقط اللاعب يستطيع تأكيد الإجابة الصحيحة.'),

('Soul Link','رابط الروح','easy',
 'How many alarms do I set in the morning before I actually get out of bed?',
 'كم منبّهاً أضع في الصباح قبل أن أقوم من الفراش فعلاً؟',
 'Only the player can confirm the right answer.',
 'فقط اللاعب يستطيع تأكيد الإجابة الصحيحة.'),

('Soul Link','رابط الروح','easy',
 'What is the one "app" on my phone that I spend way too much time on?',
 'ما هو التطبيق الواحد على هاتفي الذي أقضي فيه وقتاً أكثر مما ينبغي؟',
 'Only the player can confirm the right answer.',
 'فقط اللاعب يستطيع تأكيد الإجابة الصحيحة.'),

('Soul Link','رابط الروح','medium',
 'If I was a character in a video game, what would be my "Special Move"?',
 'لو كنت شخصية في لعبة فيديو، ما هي "حركتي الخاصة"؟',
 'Only the player can confirm the right answer.',
 'فقط اللاعب يستطيع تأكيد الإجابة الصحيحة.'),

('Soul Link','رابط الروح','easy',
 'What is the one word or phrase I say way too often?',
 'ما الكلمة أو العبارة الواحدة التي أقولها كثيراً جداً؟',
 'Only the player can confirm the right answer.',
 'فقط اللاعب يستطيع تأكيد الإجابة الصحيحة.'),

('Soul Link','رابط الروح','easy',
 'What is my favorite "low-quality" or "trashy" movie/show?',
 'ما هو فيلمي أو مسلسلي المفضّل "الرديء الجودة" أو "الابتذالي"؟',
 'Only the player can confirm the right answer.',
 'فقط اللاعب يستطيع تأكيد الإجابة الصحيحة.'),

('Soul Link','رابط الروح','medium',
 'If I had to survive in the wilderness with only three items, what would they be?',
 'لو اضطررت للبقاء في البرية مع ثلاثة أشياء فقط، ما هي؟',
 'Only the player can confirm the right answer.',
 'فقط اللاعب يستطيع تأكيد الإجابة الصحيحة.'),

('Soul Link','رابط الروح','hard',
 'What is my "hidden" obsession (something I know too much about for no reason)?',
 'ما هي هوسي "المخفي" (شيء أعرف عنه أكثر مما ينبغي بلا سبب واضح)؟',
 'Only the player can confirm the right answer.',
 'فقط اللاعب يستطيع تأكيد الإجابة الصحيحة.'),

('Soul Link','رابط الروح','hard',
 'If you had to describe my "soul" as a specific color, which color would it be?',
 'لو وصفتَ "روحي" بلون محدد، ما هذا اللون؟',
 'Only the player can confirm the right answer.',
 'فقط اللاعب يستطيع تأكيد الإجابة الصحيحة.'),

# ── Part 3: Intimacy & Bond Test ─────────────────────────────────
('Intimacy & Bond','اختبار الألفة والترابط','easy',
 'What is the one thing I do every single morning that would ruin my day if I skipped it?',
 'ما الشيء الواحد الذي أفعله كل صباح والذي سيُفسد يومي إن أغفلته؟',
 'Only your partner / closest friend knows the right answer.',
 'فقط شريكك أو صديقك المقرّب يعرف الإجابة الصحيحة.'),

('Intimacy & Bond','اختبار الألفة والترابط','easy',
 'How do I actually like my eggs/breakfast prepared (be specific)?',
 'كيف أُفضّل إعداد بيضي أو فطوري فعلاً (كن محدداً)؟',
 'Only your partner / closest friend knows the right answer.',
 'فقط شريكك أو صديقك المقرّب يعرف الإجابة الصحيحة.'),

('Intimacy & Bond','اختبار الألفة والترابط','medium',
 'What is my "social battery" limit in hours before I need to leave a party?',
 'ما حدود "طاقتي الاجتماعية" بالساعات قبل أن أحتاج لمغادرة الحفلة؟',
 'Only your partner / closest friend knows the right answer.',
 'فقط شريكك أو صديقك المقرّب يعرف الإجابة الصحيحة.'),

('Intimacy & Bond','اختبار الألفة والترابط','medium',
 'When I\'m sick, do I want to be left completely alone or do I want constant attention?',
 'حين أمرض، هل أريد أن أُترك وحيداً تماماً أم أريد اهتماماً مستمراً؟',
 'Only your partner / closest friend knows the right answer.',
 'فقط شريكك أو صديقك المقرّب يعرف الإجابة الصحيحة.'),

('Intimacy & Bond','اختبار الألفة والترابط','easy',
 'What is the one chore I absolutely hate doing more than any other?',
 'ما هي المهمة المنزلية التي أكرهها أكثر من أي شيء آخر؟',
 'Only your partner / closest friend knows the right answer.',
 'فقط شريكك أو صديقك المقرّب يعرف الإجابة الصحيحة.'),

('Intimacy & Bond','اختبار الألفة والترابط','easy',
 'Do I prefer the window seat or the aisle seat when we travel?',
 'هل أُفضّل المقعد الجانبي للنافذة أم الممر حين نسافر؟',
 'Only your partner / closest friend knows the right answer.',
 'فقط شريكك أو صديقك المقرّب يعرف الإجابة الصحيحة.'),

('Intimacy & Bond','اختبار الألفة والترابط','easy',
 'What is my "comfort" temperature for the AC at night?',
 'ما درجة حرارة المكيّف "المريحة" لي في الليل؟',
 'Only your partner / closest friend knows the right answer.',
 'فقط شريكك أو صديقك المقرّب يعرف الإجابة الصحيحة.'),

('Intimacy & Bond','اختبار الألفة والترابط','medium',
 'If I can\'t sleep, what is the first thing I usually do to try and drift off?',
 'لو لم أستطع النوم، ما أول شيء أفعله عادةً لمحاولة الاسترخاء والنوم؟',
 'Only your partner / closest friend knows the right answer.',
 'فقط شريكك أو صديقك المقرّب يعرف الإجابة الصحيحة.'),

('Intimacy & Bond','اختبار الألفة والترابط','easy',
 'What is my "default" outfit when I\'m just hanging out at home?',
 'ما هو "زيّي الافتراضي" حين أجلس في المنزل فقط؟',
 'Only your partner / closest friend knows the right answer.',
 'فقط شريكك أو صديقك المقرّب يعرف الإجابة الصحيحة.'),

('Intimacy & Bond','اختبار الألفة والترابط','easy',
 'Which side of the bed is "my" side, and do I ever actually switch?',
 'أي جانب السرير هو "جانبي"، وهل أُغيّره أحياناً فعلاً؟',
 'Only your partner / closest friend knows the right answer.',
 'فقط شريكك أو صديقك المقرّب يعرف الإجابة الصحيحة.'),

('Intimacy & Bond','اختبار الألفة والترابط','easy',
 'What is the one snack I will always finish if it\'s left in the cupboard?',
 'ما الوجبة الخفيفة التي سأنهيها دائماً إن تُركت في الخزانة؟',
 'Only your partner / closest friend knows the right answer.',
 'فقط شريكك أو صديقك المقرّب يعرف الإجابة الصحيحة.'),

('Intimacy & Bond','اختبار الألفة والترابط','medium',
 'How do I react when I\'m stuck in heavy traffic—angry, patient, or distracted?',
 'كيف أتصرف حين أعلق في زحمة مرورية — غاضباً أم صبوراً أم مشتتاً؟',
 'Only your partner / closest friend knows the right answer.',
 'فقط شريكك أو صديقك المقرّب يعرف الإجابة الصحيحة.'),

('Intimacy & Bond','اختبار الألفة والترابط','easy',
 'What is the first thing I do when I walk through the front door after work?',
 'ما أول شيء أفعله حين أدخل الباب الرئيسي بعد العمل؟',
 'Only your partner / closest friend knows the right answer.',
 'فقط شريكك أو صديقك المقرّب يعرف الإجابة الصحيحة.'),

('Intimacy & Bond','اختبار الألفة والترابط','easy',
 'Do I prefer physical books, an e-reader, or audiobooks?',
 'هل أُفضّل الكتب الورقية أم القارئ الإلكتروني أم الكتب الصوتية؟',
 'Only your partner / closest friend knows the right answer.',
 'فقط شريكك أو صديقك المقرّب يعرف الإجابة الصحيحة.'),

('Intimacy & Bond','اختبار الألفة والترابط','easy',
 'What is my go-to "bad" habit when I\'m bored (scrolling, snacking, fidgeting)?',
 'ما هي عادتي "السيئة" المفضّلة حين أشعر بالملل (التصفح أم الأكل أم التململ)؟',
 'Only your partner / closest friend knows the right answer.',
 'فقط شريكك أو صديقك المقرّب يعرف الإجابة الصحيحة.'),

('Intimacy & Bond','اختبار الألفة والترابط','very-advanced',
 'What was the exact moment you realized we were going to be a "big deal" in each other\'s lives?',
 'ما اللحظة بالضبط التي أدركت فيها أننا سنكون "مهمّين جداً" في حياة بعضنا؟',
 'Only your partner / closest friend knows the right answer.',
 'فقط شريكك أو صديقك المقرّب يعرف الإجابة الصحيحة.'),

('Intimacy & Bond','اختبار الألفة والترابط','medium',
 'What was the first meal we ever ate together?',
 'ما كانت أول وجبة تناولناها معاً؟',
 'Only your partner / closest friend knows the right answer.',
 'فقط شريكك أو صديقك المقرّب يعرف الإجابة الصحيحة.'),

('Intimacy & Bond','اختبار الألفة والترابط','medium',
 'What is one story from my childhood that I\'ve told you at least ten times?',
 'ما قصة واحدة من طفولتي رويتها لك على الأقل عشر مرات؟',
 'Only your partner / closest friend knows the right answer.',
 'فقط شريكك أو صديقك المقرّب يعرف الإجابة الصحيحة.'),

('Intimacy & Bond','اختبار الألفة والترابط','medium',
 'What was my first impression of your family/closest friends?',
 'ما كان انطباعي الأول عن عائلتك أو أصدقائك المقرّبين؟',
 'Only your partner / closest friend knows the right answer.',
 'فقط شريكك أو صديقك المقرّب يعرف الإجابة الصحيحة.'),

('Intimacy & Bond','اختبار الألفة والترابط','hard',
 'What is the most meaningful gift I\'ve ever given you (not the most expensive)?',
 'ما أكثر هدية مؤثرة قدّمتها لك على الإطلاق (وليس الأغلى ثمناً)؟',
 'Only your partner / closest friend knows the right answer.',
 'فقط شريكك أو صديقك المقرّب يعرف الإجابة الصحيحة.'),

('Intimacy & Bond','اختبار الألفة والترابط','easy',
 'What is one fashion choice I made in the past that you are glad I moved on from?',
 'ما هو اختيار أزياء قديم اتخذته وتشعر بالارتياح لأنني تجاوزته؟',
 'Only your partner / closest friend knows the right answer.',
 'فقط شريكك أو صديقك المقرّب يعرف الإجابة الصحيحة.'),

('Intimacy & Bond','اختبار الألفة والترابط','very-advanced',
 'What was the biggest "crisis" we navigated together, and how did it change us?',
 'ما أكبر "أزمة" تجاوزناها معاً، وكيف غيّرتنا؟',
 'Only your partner / closest friend knows the right answer.',
 'فقط شريكك أو صديقك المقرّب يعرف الإجابة الصحيحة.'),

('Intimacy & Bond','اختبار الألفة والترابط','medium',
 'What is the one song that instantly reminds me of our early days?',
 'ما الأغنية الواحدة التي تُذكّرك فوراً بأيامنا الأولى؟',
 'Only your partner / closest friend knows the right answer.',
 'فقط شريكك أو صديقك المقرّب يعرف الإجابة الصحيحة.'),

('Intimacy & Bond','اختبار الألفة والترابط','medium',
 'What was the name of my first pet, and what happened to it?',
 'ما اسم حيواني الأليف الأول، وماذا حدث له؟',
 'Only your partner / closest friend knows the right answer.',
 'فقط شريكك أو صديقك المقرّب يعرف الإجابة الصحيحة.'),

('Intimacy & Bond','اختبار الألفة والترابط','medium',
 'Where was the first place we ever traveled together, and what went wrong on that trip?',
 'أين كان أول مكان سافرنا إليه معاً، وما الذي سار بشكل خاطئ في تلك الرحلة؟',
 'Only your partner / closest friend knows the right answer.',
 'فقط شريكك أو صديقك المقرّب يعرف الإجابة الصحيحة.'),

('Intimacy & Bond','اختبار الألفة والترابط','very-advanced',
 'What is the one thing I am most sensitive about that I rarely talk to others about?',
 'ما الشيء الذي أكون أكثر حساسية تجاهه ونادراً ما أتحدث عنه مع الآخرين؟',
 'Only your partner / closest friend knows the right answer.',
 'فقط شريكك أو صديقك المقرّب يعرف الإجابة الصحيحة.'),

('Intimacy & Bond','اختبار الألفة والترابط','hard',
 'When I\'m crying, what is the most helpful thing you can do for me?',
 'حين أبكي، ما أكثر شيء مفيد يمكنك فعله لي؟',
 'Only your partner / closest friend knows the right answer.',
 'فقط شريكك أو صديقك المقرّب يعرف الإجابة الصحيحة.'),

('Intimacy & Bond','اختبار الألفة والترابط','hard',
 'What is my "primary" love language—and what is my "secondary" one?',
 'ما هي لغة حبي "الأساسية" وما هي "الثانوية"؟',
 'Only your partner / closest friend knows the right answer.',
 'فقط شريكك أو صديقك المقرّب يعرف الإجابة الصحيحة.'),

('Intimacy & Bond','اختبار الألفة والترابط','hard',
 'What is the one thing you do that makes me feel the most safe and secure?',
 'ما الشيء الواحد الذي تفعله والذي يجعلني أشعر بأكبر قدر من الأمان؟',
 'Only your partner / closest friend knows the right answer.',
 'فقط شريكك أو صديقك المقرّب يعرف الإجابة الصحيحة.'),

('Intimacy & Bond','اختبار الألفة والترابط','medium',
 'How do I handle failure—do I get motivated, or do I need time to sulk?',
 'كيف أتعامل مع الفشل — هل يدفعني للأمام أم أحتاج وقتاً للتسخّط؟',
 'Only your partner / closest friend knows the right answer.',
 'فقط شريكك أو صديقك المقرّب يعرف الإجابة الصحيحة.'),

('Intimacy & Bond','اختبار الألفة والترابط','very-advanced',
 'What is my biggest "unspoken" fear about the future?',
 'ما أكبر خوفي "غير المُعلن" من المستقبل؟',
 'Only your partner / closest friend knows the right answer.',
 'فقط شريكك أو صديقك المقرّب يعرف الإجابة الصحيحة.'),

('Intimacy & Bond','اختبار الألفة والترابط','hard',
 'What is the one personality trait of mine that I am secretly proud of?',
 'ما هي السمة الشخصية الواحدة التي أفخر بها سراً في نفسي؟',
 'Only your partner / closest friend knows the right answer.',
 'فقط شريكك أو صديقك المقرّب يعرف الإجابة الصحيحة.'),

('Intimacy & Bond','اختبار الألفة والترابط','hard',
 'If I\'m having a "low-confidence" day, what is the one compliment that actually works?',
 'لو كنت في يوم "ثقة منخفضة"، ما المديح الواحد الذي يصلح معي فعلاً؟',
 'Only your partner / closest friend knows the right answer.',
 'فقط شريكك أو صديقك المقرّب يعرف الإجابة الصحيحة.'),

('Intimacy & Bond','اختبار الألفة والترابط','hard',
 'What is the one thing about my physical appearance that I am most self-conscious about?',
 'ما الشيء الواحد في مظهري الجسدي الذي أكون أكثر وعياً به وحرجاً منه؟',
 'Only your partner / closest friend knows the right answer.',
 'فقط شريكك أو صديقك المقرّب يعرف الإجابة الصحيحة.'),

('Intimacy & Bond','اختبار الألفة والترابط','very-advanced',
 'Do I believe in "soulmates," or do I believe relationships are built purely on choice?',
 'هل أؤمن بـ"التوأم الروحي" أم أعتقد أن العلاقات مبنية على الاختيار البحت؟',
 'Only your partner / closest friend knows the right answer.',
 'فقط شريكك أو صديقك المقرّب يعرف الإجابة الصحيحة.'),

('Intimacy & Bond','اختبار الألفة والترابط','medium',
 'If we could move to any city in the world tomorrow, where would I want to go?',
 'لو أمكننا الانتقال لأي مدينة في العالم غداً، أين سأريد أن أذهب؟',
 'Only your partner / closest friend knows the right answer.',
 'فقط شريكك أو صديقك المقرّب يعرف الإجابة الصحيحة.'),

('Intimacy & Bond','اختبار الألفة والترابط','medium',
 'What is the one "bucket list" item I want us to do before we turn 50?',
 'ما الشيء الواحد في قائمة أمنياتي الذي أريد أن نفعله معاً قبل أن نبلغ الخمسين؟',
 'Only your partner / closest friend knows the right answer.',
 'فقط شريكك أو صديقك المقرّب يعرف الإجابة الصحيحة.'),

('Intimacy & Bond','اختبار الألفة والترابط','hard',
 'Do I want to be "rich and famous" or "comfortable and anonymous"?',
 'هل أريد أن أكون "غنياً ومشهوراً" أم "مرتاحاً ومجهولاً"؟',
 'Only your partner / closest friend knows the right answer.',
 'فقط شريكك أو صديقك المقرّب يعرف الإجابة الصحيحة.'),

('Intimacy & Bond','اختبار الألفة والترابط','medium',
 'What is the one cause or charity I would donate a million dollars to?',
 'ما القضية أو الجمعية الخيرية الواحدة التي أتبرع لها بمليون دولار؟',
 'Only your partner / closest friend knows the right answer.',
 'فقط شريكك أو صديقك المقرّب يعرف الإجابة الصحيحة.'),

('Intimacy & Bond','اختبار الألفة والترابط','easy',
 'If we won the lottery, what is the first "unnecessary" luxury I\'d buy?',
 'لو ربحنا اليانصيب، ما أول "رفاهية غير ضرورية" سأشتريها؟',
 'Only your partner / closest friend knows the right answer.',
 'فقط شريكك أو صديقك المقرّب يعرف الإجابة الصحيحة.'),

('Intimacy & Bond','اختبار الألفة والترابط','medium',
 'What is my "dream" home style (modern, rustic, apartment, villa)?',
 'ما هو طراز منزل أحلامي (عصري، ريفي، شقة، فيلا)؟',
 'Only your partner / closest friend knows the right answer.',
 'فقط شريكك أو صديقك المقرّب يعرف الإجابة الصحيحة.'),

('Intimacy & Bond','اختبار الألفة والترابط','medium',
 'How many kids (or pets) did I originally say I wanted?',
 'كم عدد الأطفال (أو الحيوانات الأليفة) الذي قلت في الأصل أنني أريده؟',
 'Only your partner / closest friend knows the right answer.',
 'فقط شريكك أو صديقك المقرّب يعرف الإجابة الصحيحة.'),

('Intimacy & Bond','اختبار الألفة والترابط','hard',
 'What is the one career goal I\'m still chasing, even if I don\'t mention it often?',
 'ما الهدف المهني الواحد الذي لا أزال أسعى إليه حتى لو لا أذكره كثيراً؟',
 'Only your partner / closest friend knows the right answer.',
 'فقط شريكك أو صديقك المقرّب يعرف الإجابة الصحيحة.'),

('Intimacy & Bond','اختبار الألفة والترابط','medium',
 'If I could retire today, what would I spend my Tuesdays doing?',
 'لو تقاعدت اليوم، بماذا سأقضي أيام الثلاثاء؟',
 'Only your partner / closest friend knows the right answer.',
 'فقط شريكك أو صديقك المقرّب يعرف الإجابة الصحيحة.'),

('Intimacy & Bond','اختبار الألفة والترابط','very-advanced',
 'What is the "legacy" I want to leave behind?',
 'ما هو "الإرث" الذي أريد تركه خلفي؟',
 'Only your partner / closest friend knows the right answer.',
 'فقط شريكك أو صديقك المقرّب يعرف الإجابة الصحيحة.'),

('Intimacy & Bond','اختبار الألفة والترابط','hard',
 'Who is the one person in my life I look up to the most?',
 'من هو الشخص الواحد في حياتي الذي أُجلّه أكثر من غيره؟',
 'Only your partner / closest friend knows the right answer.',
 'فقط شريكك أو صديقك المقرّب يعرف الإجابة الصحيحة.'),

('Intimacy & Bond','اختبار الألفة والترابط','medium',
 'How do I act when I\'m meeting someone new that I\'m trying to impress?',
 'كيف أتصرف حين أقابل شخصاً جديداً أحاول إبهاره؟',
 'Only your partner / closest friend knows the right answer.',
 'فقط شريكك أو صديقك المقرّب يعرف الإجابة الصحيحة.'),

('Intimacy & Bond','اختبار الألفة والترابط','medium',
 'What is my "pet peeve" when it comes to other people\'s behavior in public?',
 'ما هو "المضايقة الصغيرة" التي تزعجني في سلوك الناس في الأماكن العامة؟',
 'Only your partner / closest friend knows the right answer.',
 'فقط شريكك أو صديقك المقرّب يعرف الإجابة الصحيحة.'),

('Intimacy & Bond','اختبار الألفة والترابط','medium',
 'Do I prefer small, intimate dinners or large, loud parties?',
 'هل أُفضّل العشاءات الصغيرة الحميمة أم الحفلات الكبيرة الصاخبة؟',
 'Only your partner / closest friend knows the right answer.',
 'فقط شريكك أو صديقك المقرّب يعرف الإجابة الصحيحة.'),

('Intimacy & Bond','اختبار الألفة والترابط','hard',
 'What is the one thing my "best friend" knows about me that you also know?',
 'ما الشيء الواحد الذي يعرفه "صديقي المقرّب" عني والذي تعرفه أنت أيضاً؟',
 'Only your partner / closest friend knows the right answer.',
 'فقط شريكك أو صديقك المقرّب يعرف الإجابة الصحيحة.'),

('Intimacy & Bond','اختبار الألفة والترابط','hard',
 'How do I handle it when I feel "left out" of a conversation?',
 'كيف أتعامل حين أشعر بأنني "مُستثنى" من محادثة ما؟',
 'Only your partner / closest friend knows the right answer.',
 'فقط شريكك أو صديقك المقرّب يعرف الإجابة الصحيحة.'),

('Intimacy & Bond','اختبار الألفة والترابط','medium',
 'Am I the "planner" in our relationship, or am I the one who goes with the flow?',
 'هل أنا "المخطِّط" في علاقتنا أم من يسير مع التيار؟',
 'Only your partner / closest friend knows the right answer.',
 'فقط شريكك أو صديقك المقرّب يعرف الإجابة الصحيحة.'),

('Intimacy & Bond','اختبار الألفة والترابط','very-advanced',
 'What is the one "secret" about someone else that I\'ve trusted you with?',
 'ما السر الواحد المتعلق بشخص آخر الذي وثقتك به؟',
 'Only your partner / closest friend knows the right answer.',
 'فقط شريكك أو صديقك المقرّب يعرف الإجابة الصحيحة.'),

('Intimacy & Bond','اختبار الألفة والترابط','medium',
 'If someone is rude to me in public, do I confront them or walk away?',
 'لو كان شخص ما وقحاً معي في الأماكن العامة، هل أواجهه أم أبتعد؟',
 'Only your partner / closest friend knows the right answer.',
 'فقط شريكك أو صديقك المقرّب يعرف الإجابة الصحيحة.'),

('Intimacy & Bond','اختبار الألفة والترابط','easy',
 'What is my favorite "inside joke" that we have with each other?',
 'ما هي نكتتنا "الداخلية" المفضّلة التي نتشاركها؟',
 'Only your partner / closest friend knows the right answer.',
 'فقط شريكك أو صديقك المقرّب يعرف الإجابة الصحيحة.'),

('Intimacy & Bond','اختبار الألفة والترابط','easy',
 'What is the one movie I can watch over and over without getting bored?',
 'ما الفيلم الواحد الذي أستطيع مشاهدته مراراً دون أن أشعر بالملل؟',
 'Only your partner / closest friend knows the right answer.',
 'فقط شريكك أو صديقك المقرّب يعرف الإجابة الصحيحة.'),

('Intimacy & Bond','اختبار الألفة والترابط','easy',
 'Am I a "clean freak" or "organized chaos"?',
 'هل أنا "مهووس النظافة" أم "الفوضى المنظّمة"؟',
 'Only your partner / closest friend knows the right answer.',
 'فقط شريكك أو صديقك المقرّب يعرف الإجابة الصحيحة.'),

('Intimacy & Bond','اختبار الألفة والترابط','easy',
 'What is the one smell that instantly makes me happy (coffee, rain, a certain perfume)?',
 'ما الرائحة الواحدة التي تُسعدني فوراً (قهوة، مطر، عطر معين)؟',
 'Only your partner / closest friend knows the right answer.',
 'فقط شريكك أو صديقك المقرّب يعرف الإجابة الصحيحة.'),

('Intimacy & Bond','اختبار الألفة والترابط','easy',
 'Do I prefer the city skyline or a mountain view?',
 'هل أُفضّل أفق المدينة أم المنظر الجبلي؟',
 'Only your partner / closest friend knows the right answer.',
 'فقط شريكك أو صديقك المقرّب يعرف الإجابة الصحيحة.'),

('Intimacy & Bond','اختبار الألفة والترابط','easy',
 'What is the one food I "hated" as a kid but love now?',
 'ما الطعام الذي كنت "أكرهه" طفلاً لكنني أحبه الآن؟',
 'Only your partner / closest friend knows the right answer.',
 'فقط شريكك أو صديقك المقرّب يعرف الإجابة الصحيحة.'),

('Intimacy & Bond','اختبار الألفة والترابط','easy',
 'If I\'m on a long flight, do I sleep the whole time or watch 5 movies?',
 'لو كنت في رحلة جوية طويلة، هل أنام طوال الوقت أم أشاهد 5 أفلام؟',
 'Only your partner / closest friend knows the right answer.',
 'فقط شريكك أو صديقك المقرّب يعرف الإجابة الصحيحة.'),

('Intimacy & Bond','اختبار الألفة والترابط','easy',
 'What is my "star sign," and do I actually believe in it?',
 'ما هو برجي، وهل أؤمن به فعلاً؟',
 'Only your partner / closest friend knows the right answer.',
 'فقط شريكك أو صديقك المقرّب يعرف الإجابة الصحيحة.'),

('Intimacy & Bond','اختبار الألفة والترابط','medium',
 'What is my favorite way to be woken up (or is it better to just let me sleep)?',
 'ما هي طريقتي المفضّلة للاستيقاظ (أم أنه من الأفضل تركي أنام)؟',
 'Only your partner / closest friend knows the right answer.',
 'فقط شريكك أو صديقك المقرّب يعرف الإجابة الصحيحة.'),

('Intimacy & Bond','اختبار الألفة والترابط','medium',
 'What is the one "talent" I have that is completely useless?',
 'ما هي الموهبة الواحدة التي أمتلكها وهي عديمة الفائدة تماماً؟',
 'Only your partner / closest friend knows the right answer.',
 'فقط شريكك أو صديقك المقرّب يعرف الإجابة الصحيحة.'),

('Intimacy & Bond','اختبار الألفة والترابط','medium',
 'If I were a fictional character (book/movie), who would I be?',
 'لو كنت شخصية خيالية (من كتاب أو فيلم)، من سأكون؟',
 'Only your partner / closest friend knows the right answer.',
 'فقط شريكك أو صديقك المقرّب يعرف الإجابة الصحيحة.'),

('Intimacy & Bond','اختبار الألفة والترابط','medium',
 'What is the first thing I look at when I meet a stranger?',
 'ما أول شيء ألاحظه حين أقابل غريباً؟',
 'Only your partner / closest friend knows the right answer.',
 'فقط شريكك أو صديقك المقرّب يعرف الإجابة الصحيحة.'),

('Intimacy & Bond','اختبار الألفة والترابط','medium',
 'Do I like "surprises," or do they make me anxious?',
 'هل أُحبّ "المفاجآت" أم تُقلقني؟',
 'Only your partner / closest friend knows the right answer.',
 'فقط شريكك أو صديقك المقرّب يعرف الإجابة الصحيحة.'),

('Intimacy & Bond','اختبار الألفة والترابط','easy',
 'What is the one thing I always forget to do (like locking the door or charging my phone)?',
 'ما الشيء الذي أنساه دائماً (كإغلاق الباب أو شحن هاتفي)؟',
 'Only your partner / closest friend knows the right answer.',
 'فقط شريكك أو صديقك المقرّب يعرف الإجابة الصحيحة.'),

('Intimacy & Bond','اختبار الألفة والترابط','hard',
 'What is the one thing you do that drives me absolutely crazy (but I still love you)?',
 'ما الشيء الواحد الذي تفعله والذي يُجنّني تماماً (لكنني لا أزال أحبك)؟',
 'Only your partner / closest friend knows the right answer.',
 'فقط شريكك أو صديقك المقرّب يعرف الإجابة الصحيحة.'),

('Intimacy & Bond','اختبار الألفة والترابط','very-advanced',
 'What is the most "romantic" thing we\'ve ever done that didn\'t cost a cent?',
 'ما أكثر شيء "رومانسي" فعلناه ولم يكلف قرشاً واحداً؟',
 'Only your partner / closest friend knows the right answer.',
 'فقط شريكك أو صديقك المقرّب يعرف الإجابة الصحيحة.'),

('Intimacy & Bond','اختبار الألفة والترابط','very-advanced',
 'What is my stance on "forgiveness"—do I believe everyone deserves a second chance?',
 'ما موقفي من "العفو" — هل أؤمن أن الجميع يستحق فرصة ثانية؟',
 'Only your partner / closest friend knows the right answer.',
 'فقط شريكك أو صديقك المقرّب يعرف الإجابة الصحيحة.'),

('Intimacy & Bond','اختبار الألفة والترابط','very-advanced',
 'What is the one thing I would never, ever forgive a person for?',
 'ما الشيء الواحد الذي لن أسامح عليه أبداً؟',
 'Only your partner / closest friend knows the right answer.',
 'فقط شريكك أو صديقك المقرّب يعرف الإجابة الصحيحة.'),

('Intimacy & Bond','اختبار الألفة والترابط','hard',
 'How much of my "identity" is tied to my career?',
 'كم مقدار ارتباط "هويتي" بمسيرتي المهنية؟',
 'Only your partner / closest friend knows the right answer.',
 'فقط شريكك أو صديقك المقرّب يعرف الإجابة الصحيحة.'),

('Intimacy & Bond','اختبار الألفة والترابط','hard',
 'Do I prioritize "adventure" or "security"?',
 'هل أُولوي "المغامرة" أم "الأمان"؟',
 'Only your partner / closest friend knows the right answer.',
 'فقط شريكك أو صديقك المقرّب يعرف الإجابة الصحيحة.'),

('Intimacy & Bond','اختبار الألفة والترابط','very-advanced',
 'What is my biggest "non-negotiable" in a relationship?',
 'ما هو أكبر "خط أحمر" لا أتنازل عنه في علاقة؟',
 'Only your partner / closest friend knows the right answer.',
 'فقط شريكك أو صديقك المقرّب يعرف الإجابة الصحيحة.'),

('Intimacy & Bond','اختبار الألفة والترابط','very-advanced',
 'What is the one thing I want people to say about me at my 80th birthday party?',
 'ما الشيء الذي أريد أن يقوله الناس عني في حفلة عيد ميلادي الثمانين؟',
 'Only your partner / closest friend knows the right answer.',
 'فقط شريكك أو صديقك المقرّب يعرف الإجابة الصحيحة.'),

('Intimacy & Bond','اختبار الألفة والترابط','very-advanced',
 'Do I think I am a "good person," or am I always trying to be "better"?',
 'هل أعتقد أنني "شخص جيد" أم أنني دائماً أسعى لأكون "أفضل"؟',
 'Only your partner / closest friend knows the right answer.',
 'فقط شريكك أو صديقك المقرّب يعرف الإجابة الصحيحة.'),

('Intimacy & Bond','اختبار الألفة والترابط','very-advanced',
 'What is the one "lesson" from my parents that I am trying NOT to repeat?',
 'ما الدرس الواحد من والديّ الذي أحاول ألّا أكرّره؟',
 'Only your partner / closest friend knows the right answer.',
 'فقط شريكك أو صديقك المقرّب يعرف الإجابة الصحيحة.'),

('Intimacy & Bond','اختبار الألفة والترابط','very-advanced',
 'What is the one thing I would change about my past if I had a time machine?',
 'ما الشيء الواحد الذي سأُغيّره في ماضيّ لو امتلكت آلة زمن؟',
 'Only your partner / closest friend knows the right answer.',
 'فقط شريكك أو صديقك المقرّب يعرف الإجابة الصحيحة.'),

('Intimacy & Bond','اختبار الألفة والترابط','very-advanced',
 'If the world was ending in 24 hours, what would be our final 3 activities?',
 'لو كان العالم سينتهي خلال 24 ساعة، ما هي أنشطتنا الثلاث الأخيرة؟',
 'Only your partner / closest friend knows the right answer.',
 'فقط شريكك أو صديقك المقرّب يعرف الإجابة الصحيحة.'),

('Intimacy & Bond','اختبار الألفة والترابط','very-advanced',
 'What is the specific look I give you when I want us to leave a boring event early?',
 'ما النظرة المحددة التي أُعطيك إياها حين أريد مغادرة حدث مملّ مبكراً؟',
 'Only your partner / closest friend knows the right answer.',
 'فقط شريكك أو صديقك المقرّب يعرف الإجابة الصحيحة.'),

('Intimacy & Bond','اختبار الألفة والترابط','hard',
 'If I\'m pretending to listen but actually zoning out, what is my "fake" listening face?',
 'لو كنت أتظاهر بالإنصات لكنني في الواقع شارد الذهن، كيف يبدو وجه "الإنصات المزيّف" لديّ؟',
 'Only your partner / closest friend knows the right answer.',
 'فقط شريكك أو صديقك المقرّب يعرف الإجابة الصحيحة.'),

('Intimacy & Bond','اختبار الألفة والترابط','hard',
 'What is the exact phrase I use when I\'m about to start an argument?',
 'ما العبارة بالضبط التي أستخدمها حين أكون على وشك إشعال جدال؟',
 'Only your partner / closest friend knows the right answer.',
 'فقط شريكك أو صديقك المقرّب يعرف الإجابة الصحيحة.'),

('Intimacy & Bond','اختبار الألفة والترابط','very-advanced',
 'What is the one "secret" dream I have that I\'m actually afraid of achieving?',
 'ما الحلم "السري" الواحد الذي أمتلكه والذي أخشى في الواقع تحقيقه؟',
 'Only your partner / closest friend knows the right answer.',
 'فقط شريكك أو صديقك المقرّب يعرف الإجابة الصحيحة.'),

('Intimacy & Bond','اختبار الألفة والترابط','hard',
 'How do I act when I\'m secretly jealous?',
 'كيف أتصرف حين أكون غيوراً سراً؟',
 'Only your partner / closest friend knows the right answer.',
 'فقط شريكك أو صديقك المقرّب يعرف الإجابة الصحيحة.'),

('Intimacy & Bond','اختبار الألفة والترابط','medium',
 'What is the one thing I do when I\'m feeling really proud of myself?',
 'ما الشيء الواحد الذي أفعله حين أشعر بفخر حقيقي بنفسي؟',
 'Only your partner / closest friend knows the right answer.',
 'فقط شريكك أو صديقك المقرّب يعرف الإجابة الصحيحة.'),

('Intimacy & Bond','اختبار الألفة والترابط','very-advanced',
 'If I could "delete" one personality trait of mine, what would it be?',
 'لو أمكنني "حذف" سمة شخصية واحدة من شخصيتي، ما هي؟',
 'Only your partner / closest friend knows the right answer.',
 'فقط شريكك أو صديقك المقرّب يعرف الإجابة الصحيحة.'),

('Intimacy & Bond','اختبار الألفة والترابط','hard',
 'What is the one thing I do that makes you realize I\'m "home" and finally relaxed?',
 'ما الشيء الواحد الذي أفعله والذي يُشعرك أنني "عدت لنفسي" ومرتاح أخيراً؟',
 'Only your partner / closest friend knows the right answer.',
 'فقط شريكك أو صديقك المقرّب يعرف الإجابة الصحيحة.'),

('Intimacy & Bond','اختبار الألفة والترابط','very-advanced',
 'How do I treat people who can do nothing for me?',
 'كيف أتعامل مع الأشخاص الذين لا يستطيعون تقديم أي شيء لي؟',
 'Only your partner / closest friend knows the right answer.',
 'فقط شريكك أو صديقك المقرّب يعرف الإجابة الصحيحة.'),

('Intimacy & Bond','اختبار الألفة والترابط','medium',
 'If I were a season, would I be Spring, Summer, Autumn, or Winter?',
 'لو كنت فصلاً من فصول السنة، هل سأكون الربيع أم الصيف أم الخريف أم الشتاء؟',
 'Only your partner / closest friend knows the right answer.',
 'فقط شريكك أو صديقك المقرّب يعرف الإجابة الصحيحة.'),

('Intimacy & Bond','اختبار الألفة والترابط','very-advanced',
 'What is the "most" I\'ve ever laughed with you?',
 'ما هي اللحظة التي ضحكت فيها معك بأشد ما يمكن؟',
 'Only your partner / closest friend knows the right answer.',
 'فقط شريكك أو صديقك المقرّب يعرف الإجابة الصحيحة.'),

('Intimacy & Bond','اختبار الألفة والترابط','very-advanced',
 'What is the one thing I do that proves I know you better than anyone else?',
 'ما الشيء الواحد الذي أفعله والذي يُثبت أنني أعرفك أكثر من أي شخص آخر؟',
 'Only your partner / closest friend knows the right answer.',
 'فقط شريكك أو صديقك المقرّب يعرف الإجابة الصحيحة.'),

('Intimacy & Bond','اختبار الألفة والترابط','very-advanced',
 'What is my "hidden" insecurity about our relationship?',
 'ما هو قلقي "المخفي" بشأن علاقتنا؟',
 'Only your partner / closest friend knows the right answer.',
 'فقط شريكك أو صديقك المقرّب يعرف الإجابة الصحيحة.'),

('Intimacy & Bond','اختبار الألفة والترابط','very-advanced',
 'If I had to describe our relationship as a "genre" of movie, what would it be?',
 'لو وصفت علاقتنا كـ"نوع" من أفلام السينما، ما هو؟',
 'Only your partner / closest friend knows the right answer.',
 'فقط شريكك أو صديقك المقرّب يعرف الإجابة الصحيحة.'),

('Intimacy & Bond','اختبار الألفة والترابط','very-advanced',
 'What is the one thing I\'ve taught you that has actually changed your life?',
 'ما الشيء الواحد الذي علّمتك إياه وغيّر حياتك فعلاً؟',
 'Only your partner / closest friend knows the right answer.',
 'فقط شريكك أو صديقك المقرّب يعرف الإجابة الصحيحة.'),

('Intimacy & Bond','اختبار الألفة والترابط','very-advanced',
 'What is the one thing you\'ve taught me that has actually changed my life?',
 'ما الشيء الواحد الذي علّمتني إياه وغيّر حياتي فعلاً؟',
 'Only your partner / closest friend knows the right answer.',
 'فقط شريكك أو صديقك المقرّب يعرف الإجابة الصحيحة.'),

('Intimacy & Bond','اختبار الألفة والترابط','very-advanced',
 'If we had to switch bodies for a day, what would be the hardest part for you?',
 'لو اضطررنا لتبادل الأجساد ليوم واحد، ما أصعب جزء بالنسبة لك؟',
 'Only your partner / closest friend knows the right answer.',
 'فقط شريكك أو صديقك المقرّب يعرف الإجابة الصحيحة.'),

('Intimacy & Bond','اختبار الألفة والترابط','very-advanced',
 'What is the "soundtrack" of our life together?',
 'ما هو "الموسيقى التصويرية" لحياتنا معاً؟',
 'Only your partner / closest friend knows the right answer.',
 'فقط شريكك أو صديقك المقرّب يعرف الإجابة الصحيحة.'),

('Intimacy & Bond','اختبار الألفة والترابط','very-advanced',
 'What is the one thing I want us to be doing in 30 years?',
 'ما الشيء الواحد الذي أريد أن نكون نفعله بعد 30 عاماً؟',
 'Only your partner / closest friend knows the right answer.',
 'فقط شريكك أو صديقك المقرّب يعرف الإجابة الصحيحة.'),

('Intimacy & Bond','اختبار الألفة والترابط','very-advanced',
 'If you had to describe me in one single word, would I agree with your choice?',
 'لو وصفتني بكلمة واحدة فقط، هل سأوافق على اختيارك؟',
 'Only your partner / closest friend knows the right answer.',
 'فقط شريكك أو صديقك المقرّب يعرف الإجابة الصحيحة.'),
]

def build_hwwdykm():
    cards = []
    for i, (sub_en, sub_ar, diff, q_en, q_ar, a_en, a_ar) in enumerate(QUESTIONS, 1):
        cards.append({
            'id': f'hwdykm-{i:03d}',
            'difficulty': diff,
            'subcategory': {'en': sub_en, 'ar': sub_ar},
            'question': {'en': q_en, 'ar': q_ar},
            'answer': {'en': a_en, 'ar': a_ar},
        })
    diff_counts = {}
    for c in cards:
        diff_counts[c['difficulty']] = diff_counts.get(c['difficulty'], 0) + 1
    return {
        'slug': 'how-well-do-you-know-me',
        'title': {'en': 'How Well Do You Know Me?', 'ar': 'كم تعرفني؟'},
        'description': {
            'en': '200 questions across three game modes: Group Dynamic, Soul Link, and Intimacy & Bond Test.',
            'ar': '200 سؤال عبر ثلاثة أوضاع لعب: ديناميكية المجموعة، رابط الروح، واختبار الألفة والترابط.'
        },
        'cluster': {'en': 'Fun & Play', 'ar': 'متعة ولعب'},
        'cluster_key': 'fun',
        'emoji': '🫶',
        'mode': 'quiz',
        'count': len(cards),
        'difficultyCounts': diff_counts,
        'subcategories': [
            {'en': 'Group Dynamic', 'ar': 'ديناميكية المجموعة'},
            {'en': 'Soul Link', 'ar': 'رابط الروح'},
            {'en': 'Intimacy & Bond', 'ar': 'اختبار الألفة والترابط'},
        ],
        'href': 'how-well-do-you-know-me.html',
        'image': 'assets/how-well-do-you-know-me.svg',
        'cards': cards,
    }

out = build_hwwdykm()
path = '/Users/jameelkhabaze/JAKH/site/data/how-well-do-you-know-me.json'
with open(path, 'w', encoding='utf-8') as f:
    json.dump(out, f, ensure_ascii=False, indent=2)
print(f'Written {out["count"]} cards → {path}')
