import { createHash } from 'node:crypto';

// Changes to this policy are human-reviewed source changes, never repairs.
export const POLICY_VERSION = 1;
export const GENERATORS = Object.freeze([
  'scripts/sync-catalog.mjs',
  // The public wrapper also rewrites authored navigation. That is deliberately
  // excluded: this runner may regenerate complete outputs, not edit sources.
  'scripts/generate-riddlearabia-seo.mjs',
  'scripts/generate-arabic-routes.mjs',
  'scripts/generate-search-index.mjs',
  'scripts/generate-category-art.mjs',
]);
export const CATEGORY_SLUGS = Object.freeze(`currencies linguistics tech-retro automotive survival fictional-worlds superheroes pop-culture true-crime mythology-legends art-and-painters biology books-and-quotes business-and-management chemistry civil-engineering classic-riddles logic-puzzles coding-and-design electrical-engineering flag-questions football geography geology history infrastructure-systems kids-riddles law-middle-east math mechanical-engineering medical-questions middle-east-history pharmacy philosophy physical-and-life-sciences psychology relationship-questions science social-sciences software-and-computing space-and-astrology story-mysteries tv-shows-trivia world-habits-and-etiquette environment-and-ecology ancient-civilizations inventions-and-minds animal-kingdom economics-and-finance architecture-and-landmarks music-and-performing-arts food-and-cuisines cinema-and-film-history future-tech-and-energy anime ayam-tayebeen`.split(' '));
const games = ['akshifha', 'chess', 'mastermind', 'go', 'reversi', 'codenames', 'catan', 'backgammon', 'set', 'hanabi', 'diplomacy'];
const seoPairs = [
  ['riddles', 'alghaz'], ['arabic-riddles', 'alghaz-arabiya'],
  ['logic-challenges', 'alghaz-mantiq'], ['family-riddles', 'alghaz-atfal'],
  ['general-knowledge', 'malumat-amma'], ['arabia-quiz', 'tarikh-al-arab'],
  ['spacetoon-nostalgia', 'hanin-spacetoon'], ['brain-games', 'alab-al-dimagh'],
];
export const GENERATED_OUTPUTS = Object.freeze([
  'data/catalog.json', 'data/search-index.json', 'data/search-index.en.json', 'data/search-index.ar.json',
  'collections.html', 'about.html', 'mind-lab.html', 'sitemap.xml',
  'ar/index.html', 'ar/mind-lab/index.html', 'ar/play/index.html', 'ar/daily/index.html', 'ar/privacy/index.html',
  'ar/collections/index.html', 'ar/about/index.html',
  ...games.map((slug) => `ar/games/${slug}/index.html`),
  ...seoPairs.flatMap(([en, ar]) => [`${en}.html`, `ar/${ar}/index.html`]),
  ...CATEGORY_SLUGS.flatMap((slug) => [`${slug}.html`, `ar/topics/${slug}/index.html`, `assets/${slug}.svg`]),
].sort());
const allowedOutputs = new Set(GENERATED_OUTPUTS);
export const MAX_CHANGED_FILES = 250;
export const MAX_CHANGED_BYTES = 12 * 1024 * 1024;
export const sha256 = (bytes) => createHash('sha256').update(bytes).digest('hex');

export function assertSafePath(relativePath) {
  if (typeof relativePath !== 'string' || !relativePath || relativePath.startsWith('/')
      || relativePath.includes('\\') || /[\x00-\x1f\x7f]/u.test(relativePath)
      || relativePath.split('/').some((part) => !part || part === '.' || part === '..' || part.toLowerCase() === '.git')) {
    throw new Error(`Unsafe repository path: ${JSON.stringify(relativePath)}`);
  }
}

export function assertAllowedChanges(changes) {
  if (!Array.isArray(changes)) throw new Error('Changes must be an array');
  if (changes.length > MAX_CHANGED_FILES) throw new Error(`Repair exceeds ${MAX_CHANGED_FILES} changed files`);
  const seen = new Set();
  let totalBytes = 0;
  for (const change of changes) {
    assertSafePath(change.path);
    if (seen.has(change.path)) throw new Error(`Duplicate changed path: ${change.path}`);
    seen.add(change.path);
    if (!allowedOutputs.has(change.path)) throw new Error(`Not an approved generated output: ${change.path}`);
    if (!['add', 'modify'].includes(change.change)) throw new Error(`Deletion, rename or type change is forbidden: ${change.path}`);
    if (!['100644', '100755'].includes(change.newMode)) throw new Error(`Output is not a regular file: ${change.path}`);
    if (change.change === 'add' && (change.oldMode !== null || change.newMode !== '100644')) {
      throw new Error(`New outputs must be ordinary non-executable files: ${change.path}`);
    }
    if (change.change === 'modify' && change.oldMode !== change.newMode) throw new Error(`Mode change is forbidden: ${change.path}`);
    if (!Number.isSafeInteger(change.bytes) || change.bytes < 0) throw new Error(`Invalid file size: ${change.path}`);
    totalBytes += change.bytes;
  }
  if (totalBytes > MAX_CHANGED_BYTES) throw new Error(`Repair exceeds ${MAX_CHANGED_BYTES} generated bytes`);
  return { files: changes.length, bytes: totalBytes };
}

// catalog.json also contains authored labels. Only the known derived projection
// may change; exact reproduction from the base is an additional requirement.
const derivedCategoryFields = new Set(['cluster_key', 'cluster', 'href', 'image', 'count', 'verifiedQuestionCount',
  'scorableQuestionCount', 'quickFireQuestionCount', 'reviewedQuestionCount', 'difficultyCounts', 'topics', 'related', 'subcategories']);
function authoredCatalog(catalog) {
  const copy = structuredClone(catalog);
  if (!copy || typeof copy !== 'object' || !Array.isArray(copy.categories)) throw new Error('Invalid catalog');
  if (copy.site) delete copy.site.totalQuestions;
  for (const category of copy.categories) {
    if (!CATEGORY_SLUGS.includes(category.slug)) throw new Error(`Category needs a reviewed policy update: ${category.slug}`);
    for (const key of derivedCategoryFields) delete category[key];
  }
  return copy;
}
export function assertCatalogProjection(before, after) {
  if (JSON.stringify(authoredCatalog(before)) !== JSON.stringify(authoredCatalog(after))) {
    throw new Error('Repair changes authored catalog source fields');
  }
}

export function diffSnapshots(before, after) {
  return [...new Set([...before.keys(), ...after.keys()])].sort().flatMap((relativePath) => {
    const old = before.get(relativePath);
    const next = after.get(relativePath);
    if (old && next && old.sha256 === next.sha256 && old.mode === next.mode) return [];
    return [{ path: relativePath, change: !old ? 'add' : !next ? 'delete' : 'modify',
      oldMode: old?.mode ?? null, newMode: next?.mode ?? null,
      beforeSha256: old?.sha256 ?? null, afterSha256: next?.sha256 ?? null,
      bytes: next?.bytes ?? 0 }];
  });
}
export function treeDigest(snapshot) {
  return sha256(JSON.stringify([...snapshot].sort(([a], [b]) => a < b ? -1 : a > b ? 1 : 0).map(([name, file]) => [name, file.mode, file.sha256])));
}
